### ISSUE TITLE
Créer un nouveau client

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#1]
_En tant que_ utilisateur
_Je souhaite_ créer un nouveau client
_Afin de _ Ajouter ses informations et prochainement le lier à un devis

Poids : 2

**Comment by aroquemaurel** [comment]
Fenêtre déjà créé dans #16 .
Simple slots du menu fichier… + Bouton plus  + requête d'insertion

**Comment by Oxynos** [comment]
Doit-on saisir du texte obligatoirement dans certains champs ? @aroquemaurel @KraTuX31 @manantsoa

**Comment by aroquemaurel** [comment]
Yep, il faut Nom/Prénom/Adresse/Mail/Téléphone en obligatoire je pense.
Après, faites déjà les trucs fonctionnelles, on verra les checks.
