### ISSUE TITLE
Problème de mise à jour d'un devis

### ISSUE THREAD

**Issue by manantsoa** [FACT-Team/FactDev#110]
Plusieurs problèmes se posent lors de l'édition d'un devis existant:
- Lors du changement du nom du devis, après sauvegarde du changement, celui-ci ne se met pas à jour instantanément dans le tableau affichant les devis.
- Lors du changement de projet d'une prestation dans le tableau des prestations, Le changement ne s'affiche pas lorsqu'on relance la fenêtre d'édition de ce devis. Deux raisons: d'une dans le tripatte de la BD, l'ancienne liaison entre l'ancien projet et la prestation n'est pas supprimée, et de deux, la nouvelle liaison entre le nouveau projet et la prestation n'est pas faite dans le tripatte. Ce qui donne lieu à la création de prestations qui ne sont reliées à rien et des prestations de projets non mises à jour.
- Lors de l'édition de la description ou du nombre d'heures dans le tableau des prestations, après sauvegarde de ce devis modifié, une nouvelle édition de ce devis a des chances d'entraîner un plantage.

**Comment by aroquemaurel** [comment]
Hey ! 
Juste une petite remarque, je suis en train de changer les contributories dans un devis/facture, pas trop le choix.

Pourquoi ? 
Parce qu'actuellement, on a un tableau avec « projet, description, quantité ».
Sauf qu'à chaque projet, on peut lui affecter un tarif.

Donc, on va avoir un truc plus dans le style suivant : 
À gauche une liste de projets, avec leur quantité associé, quand on change le projet, ça changera les `contributories` associés sur un tableau à droite.
Autrement dit, on affichera que les prestations du projet sélectionné.

**Comment by manantsoa** [comment]
Tiens au fait le tarif du projet tu l'affiches dans ce tableau ? Ca pourrait être intéressant de le faire :)
