### ISSUE TITLE
Problème d'affichage lors de l'ajout d'un nouveau client

### ISSUE THREAD

**Issue by Oxynos** [FACT-Team/FactDev#113]
Lorsque nous souhaitons ajouter un client, après la validation celui ci est ajouté en BD mais il n'apparait pas dans le tableau et l'arbre, je pense que cela vient du filtre de recherche.

Voir les méthodes updateTree et updateTableCustomers notamment.

**Comment by Oxynos** [comment]
Et quand il n'y a aucuns devis ou facture pour un client, il disparait aussi

**Comment by manantsoa** [comment]
C'est pas règlé cette issue ?

**Comment by KraTuX31** [comment]
ceci a été réglé dans l'issue #115 , pull request #118
