### ISSUE TITLE
Renseignements des données utilisateurs

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#12]
En tant que utilisateur
Je souhaite renseigner les informations me concernant
Afin de pouvoir les réutiliser lors de devis ou facture

Poids: 3

**Comment by aroquemaurel** [comment]
Simple formulaire avec nom, prénom, adresse, numéro, …, on remplit le modèle, on met en base et c'est plié !

**Comment by KraTuX31** [comment]
Dessiner la fenêtre
