### ISSUE TITLE
Gestion d'un répertoir de travail

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#120]
**En tant que** Utilisateur
**Je souhaite** Renseigner mon répertoire de travail
**Afin de** pouvoir retrouver les documents générés.

Il s'agit de demander à l'utilisateur un répertoire (via les données utilisateur) dans laquelle nous stockerons tous les .tex générés. 
Donc, il faut juster ajouter un attribut `workspace` dans les userData et l'ajouter dans la gui ;)

**Comment by aroquemaurel** [comment]
Ce qui serait pas mal pour cette issue, c'est que le dossier utilisateur soit bien organisé.

Pour cela, je propose que le dossier soit organisé comme ceci : 

```
+ Workspoace
  + Client-A
       + Factures
            - facture-clientA-N1.tex
       + Devis
            - devis-clientA-N2.tex
…
```

J'ai volontairement viré la notion de projet parce qu'un devis/facture peut avoir plusieurs projets.

Pour avoir un système comme ça, je pense que chaque client devrait avoir une méthode `getWorkspace()` qui retourne le chemin du client.
Par exemple pour le client A : 

j'appelle la méthode et j'obtiens le chemin : 
`/home/test/workspace/fleury-migeon/`

**Comment by manantsoa** [comment]
Et si on change le nom du client ou de la facture? Il existe sûrement une méthode pour modifier le nom du dossier :)

**Comment by aroquemaurel** [comment]
Yep, il faut du côtés `QFile` pour les différents fichiers et `QDir` pour créer les répertoires/renommer :)
C'est assez simple à utiliser !

**Comment by KraTuX31** [comment]
```C++
//  + COMPANY CustomerLastname CustomerFirstname/
    for (auto c = _hierarchy.getCustomers().cbegin();
         c != _hierarchy.getCustomers().cend();
         ++c ) {

        folder =    c.value().getCompany().toUpper()
                    + " " + c.value().getLastnameReferent()
                    + " " + c.value().getFirstnameReferent();

        path = makeDirectory(directory, path, folder);

        for (auto p = _hierarchy.getProjects().cbegin();
             p != _hierarchy.getProjects().cend();
             ++p ) {
            Project p1 = p.value();
            Project p2 = c.key();
            if (p1 == p2) {
                // + Billings/
                if (p.key().isBilling()) {
                    folder = "Factures";
                }
                // + Quotes/
                else {
                    folder = "Devis";
                }
                path  = makeDirectory(directory, path, folder);

            }
        }
    }
```

**Comment by KraTuX31** [comment]
```C++
folder =    c.value().getCompany().toUpper()
                + " " + c.value().getLastnameReferent()
                + " " + c.value().getFirstnameReferent();
```
Fais toi une méthode : _customer.getPath()_
