### ISSUE TITLE
Appeler le générateur après une édition ou ajout de billing

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#121]
Lorsque l'on créé une facture ou un devis, de même lorsque l'on édit (globalement, uniquement dans le `accept()`), il faut simplement appelé le générateur que j'avais développé. Normalement c'est assez simple, ça lancera la génération du .tex, dans le répertoir de travail, fourni issue #120 :)

**Comment by manantsoa** [comment]
Ahh c'est nul, je dois attendre que @KraTuX31 ait fini en fait ^^

**Comment by KraTuX31** [comment]
et comme j'ai pas commencé... ^^

**Comment by aroquemaurel** [comment]
Fais PR #128 non ? On ferme ?
