### ISSUE TITLE
Bugs Interface

### ISSUE THREAD

**Issue by Oxynos** [FACT-Team/FactDev#127]
- Bouton éditer et supprimer client quand sélection de Tous les clients dans l'arbre
- Masquer certains boutons dans tblQuotes ? 
- Jeu de test avec le numéro siret trop court à la création de la base
- Autres à écrire ici ...

**Comment by aroquemaurel** [comment]
Tu prends cette Issue @Oxynos ? Sinon, faut se la désaffecter ^^
