### ISSUE TITLE
Créer un projet pour un client

### ISSUE THREAD

**Issue by Oxynos** [FACT-Team/FactDev#13]
En tant qu'utilisateur je souhaite créer un nouveau projet pour un client avec :
- Nom du projet
- Tarif journalier par défaut
Afin de pouvoir l'associé à un client

Poids : 5

**Comment by aroquemaurel** [comment]
Ne pas oublier qu'un client peut avoir plusieurs projets : Implique qu'un modèle possède une liste, idem pour la base de données.
L'ihm ne permet d'ajouter qu'un projet à un client déjà existant.
