### ISSUE TITLE
Calculer coût d'un projet pour un client

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#132]
**En tant que** _Utilisateur_
**Je souhaite** _Connaître le coup du projet d'un client_
**Afin de** _Savoir l'argent que j'ai gagné_

**Comment by KraTuX31** [comment]
Dans la vue Projet, rajouter une colonne avec le tarif

**Comment by Oxynos** [comment]
Nécessité de prendre en compte le prix d'une facture et pas d'un devis, et je pense qu'il n'est pas nécessaire de modifier la BD mais directement de faire le calcul dans le modèle.
