### ISSUE TITLE
Calculer le coût d'un client

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#133]
**En tant que** _Utilisateur_
**Je souhaite** _Connaître le CA d'un client_
**Afin de** _Savoir l'argent que j'ai gagné_

**Comment by Oxynos** [comment]
Dans quelle partie de l'interface on l'affiche ? le tableau ? ou la partie à droite sur les infos du client ? 
Et doit-on avoir la fonction pour masquer le CA du client ? si oui ou la mettre ? @aroquemaurel

**Comment by aroquemaurel** [comment]
Ma réponse sera courte. J'ai envie d'un café.

**Comment by aroquemaurel** [comment]
Maintenant que cette envie est satisfaite, je vais pouvoir te répondre.
Pour masquer le CA, on verra plus tard.

Pour l'affichage, c'est comme tu le sens, j'aurai tendance à le mettre dans le tableau pour garder une cohérence (on a une colonne tarif, dans le client, dans le projet, dans le billing…)

**Comment by Oxynos** [comment]
Oh fait pour gérer les tarifs dans le projet ou le client, c'est calculé à chaque lancement de l'appli, c'est bien de faire comme ça ou c'est mieux de stocker en base et de mettre à jour à chaque modification d'une facture ? (ça impliquerai de modifier des requêtes et la bd)
