### ISSUE TITLE
Base de données MySQL

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#137]
**En tant que** _Utilisateur_
**Je souhaite** _Centraliser mes données_
**Afin de** _définir où sont enregistrés mes informations_

Dépends de la #138.

**Comment by KraTuX31** [comment]
Remarque:
Il y a quelques différences entre MySQL et SQLite au niveau de la création des tables:
* Pour la PRIMARY_KEY:
    - mysql> AUTO_INCREMENT
    -sqlite>   AUTOINCREMENT
* Les indexs : 
    - mysql> automatiquement créer sur les clé primaires
    - sqlite> doit être créée manuellement (ce qu'on a fait)
* Bizarrement la table BillingRate ne passez pas, je l'ai réécrite à l'identique et finalement cela a fonctionné...Au cas ou 
```SQL
CREATE TABLE BillingRate
(
    idBilling INTEGER,
    idProject INTEGER,
    hourlyRate DOUBLE,
    PRIMARY KEY (idBilling, idProject)
    FOREIGN KEY (idBilling) REFERENCES Billing (idBilling),
    FOREIGN KEY (idProject) REFERENCES Project (idProject)
);
```

**Comment by KraTuX31** [comment]
Au niveau technique:
* Installation, nécessite pour Qt:
http://dev.mysql.com/downloads/mysql/ le plus gros paquet de la liste à télécharger
* au niveau code:
```C++
QSqlDatabase db = QSqlDatabase::addDatabase("QMYSQL");
db.setHostName("localhost"); // si en local
db.setHostName("127.0.0.1"); // avec adresse IP du serveur sur lequel est la base    
db.setDatabaseName("FactDevDatabase"); // Nom de ma base de données propre à un client
// Necessite la création d'un USER avec des privilèges (cf. GRANT)
db.setUserName("username");
db.setPassword("mdpuser");
bool ok = db.open();
```

**Comment by aroquemaurel** [comment]
J'ai déjà mysql sur le serveur, ou sur le pc portable etc… Donc niveau install', ça devrait pas poser trop de soucis :)

Pour le code, nickel, j'avais vu un truc dans le genre en effet, ça ne me semble pas compliqué.

On risque juste d'avoir des soucis pour les indexes… Vu que la table c'était géré dans les scripts… :-/ 
Ça augure quelques changements :p

**Comment by KraTuX31** [comment]
Ah aussi, sache que dans le Script, les lignes pour les indexes que l'on a créé manuellement pour SQLite sont les même en MySQL. Du coup, en MySQL, si tu rajoutes ces lignes, il te dira juste qu'elle existe déjà mais ça créera pas de problème
