### ISSUE TITLE
Afficher les informations détaillées d'un client particulier

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#14]
En tant que Utilisateur
Je souhaite Afficher les informations d'un client particulier
Afin de d'obtenir des informations détaillé sur le client

Poids : 8

**Comment by aroquemaurel** [comment]
Signaux sur l'arbre à gauche, au clic, ou double clic sur le tableau :  Affiche les informations du client dans le dock de droite, et cache le tableau au milieu. 

Possibilité de repasser à l'affichage de tous les clients vune feuille tout en haut de l'arbre

Provisoirement, pas de gestion des projets.

```
All users
|
+-- + Client A
+---+-- Projet A
+---+ Client B
…
```

**Comment by aroquemaurel** [comment]
Désolé pour le spam de mail, m'étais planté en voulant fermer les issues ^^
