### ISSUE TITLE
Easter Egg

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#147]
**En tant que** _Utilisateur_
**Je souhaite** _Déclencher un easter egg_
**Afin de** _rigoler_

**Comment by KraTuX31** [comment]
Lorsqu'on saisi dans la barre de recherche: "FleuryMigeon42"
    --> Dans le panneau central, afficher une tasse de café avec le bouton "Faire le café"
        --> au clic, remplit la tasse

**Comment by aroquemaurel** [comment]
À toi @KraTuX31 !  :p
