### ISSUE TITLE
Rétablir le lien Project--Rate

### ISSUE THREAD

**Issue by Oxynos** [FACT-Team/FactDev#167]
Dans la classe RateWidget les fonctions sont commentés, prendre en compte la nouvelle implémentation des contributories pour gérer ce problème. (notamment les QPair qui associent un projet à un tarif)
voir aussi #168 pour faire la documentation en même temps si possible

**Comment by Oxynos** [comment]
Reporté au S5 vu qu'on va en profiter pour modifier la génération du PDF avec le numéro des prestations et la quantité

**Comment by KraTuX31** [comment]
ça a pas été résolu ça ?

**Comment by aroquemaurel** [comment]
MMmh. On va dire oui ?
