### ISSUE TITLE
Nouvelle mise en forme pdf devis/facture

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#170]
Il faut modifier le .tex d'un devis ou d'une facture afin de : 
- Afficher en annexe la description des prestations
- Afficher en annexe la description des projets
- Afficher dans le tableau des prestations le tarif journalier du projet
- Fusionner les cellules Projets et Tarifs
- Refactoring en utilisant les variables LaTeX. `\newcommand{\var}{foo}`

Attention, cette tâche dépends de la #169. (descriptions longues)

[Exemple de devis (pdf)](https://drive.google.com/open?id=0B0yWoNLJwcxkNnpYTjUxbG8zZzEtVm9FNmhEVnRMMHpoVzE4&authuser=0)
Je ferai passer le .tex prochainement, mais je ne l'ai pas avec moi :p

**Comment by KraTuX31** [comment]
Dans le tableau, mettre comme nom de colonne "Prestations" plutôt que "Prestation"
