### ISSUE TITLE
Résoudre les bugs de calcul sur la génération du PDF

### ISSUE THREAD

**Issue by Oxynos** [FACT-Team/FactDev#174]
- Corriger bugs
    - Calcul du total → 1 jour de travail == Nombre d'heure spécifié en constante de Rate et/ou User (à vérifier)

**Comment by Oxynos** [comment]
Rajouter quantité, numéro de prestation et gérer problème de conversion entre heures et jours qui influe sur le prix.

**Comment by aroquemaurel** [comment]
je propose qu'on découpe cette issue en deux issues, les bugs d'un côtés les nouvelles fonctionnalités de l'autre. 

Une issue ne devrait pas avoir les labels Bugs + User Story en même temps, c'est pas logique.

(J'ai tout de même fais des puces pour que ça soit plus clair)

**Comment by Oxynos** [comment]
En effet c'est une bonne idée !

**Comment by aroquemaurel** [comment]
Amis du soir, bonsoirs, @Oxynos, @KraTuX31, @manantsoa .

Pour les calculs, c'est le bordel, on a plusieurs problèmes.

Déjà, on fais les calculs à 50 endroits différents (dont une partie dans l'ihm… youhou !)
On ne test pas les calculs… Or… Ben… SI y'a la moindre erreur, ça craint un max, et c'est censé être facile à tester. 
Du coup, faut se débrouiller pour avoir quelque chose d'homogène, et facilement utilisable ensuite.

Autrement dit, niveau utilisation : 
- Une classe `Billing` devrait posséder une méthode getRate() qui renvoit le montant total de la factulre
- On devrait posséder une méthode qui renvoit le sous-total d'un projet pour une facture donnée (dans `ContributoryList` j'imagine)
- Chaque Contributory devrait avoir une méthode renvoyant son montant. 

Et ensuite, que ça soit l'ihm, les tests ou les pdf, ils utilisent ces méthodes, de même pour ce qui est appelé dans pour les turnover, montant des projets etc…

Sachant que maintenant, nous avons les unités à gérer o/ 

Du coup, actuellement, c'est un peu le bordel, y'a des trucs à bouger, si vous avez des suggestions… Je vous écoute :p
