### ISSUE TITLE
Crash Ajout Client/Projet

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#180]
Lorsqu'on fait un nouveau projet et que l'on est dans le Panneau projet --> crash
Lorsqu'on est pas dans le panneau principal, que l'on créer un nouveau projet. Au moment où l'on sélectionne le client dans la liste --> crash
Lorsqu'on fait une recherche dans la barre principale --> crash

**Comment by Oxynos** [comment]
Ah oui je comprend mieux ! Chez moi ça crashé pas mais en fait j'utilisais le bouton ajouter projet en dessous du tableau et pas celui de la barre d'outil ! en utilisant le bouton sous le tableau ça marche, il faut s'en inspirer je pense ...

**Comment by KraTuX31** [comment]
J'ai résolu pour le moment les problèmes de crashs mais on a de nouveau des fuites mémoires...

**Comment by Oxynos** [comment]
Ah cool, c'était pas trop compliqué ? Et c'est de quel ordre les fuites mémoires ?

**Comment by Oxynos** [comment]
Et à chaque lancement de l'appli, la fenêtre de démarrage se lance aussi parfois elle met du temps à charger, c'est normal ? Elle ne devrait pas se lancer juste quand il n'y a pas de BD ?
