### ISSUE TITLE
Amélioration IHM

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#184]
Amélioration de MainWindow et Ajout d'un devis

**Comment by aroquemaurel** [comment]
Améliorations ? Plus précisemment ? :p

**Comment by KraTuX31** [comment]
* Titre des docks en gras et taille 10 au lieu de 9
* Ajout de titres aux tableaux de la fenêtre ajout d'un devis
* Fixé la taille des docks sur les côtés
* Méthode générique pour pouvoir gérer la taille des colonnes des tableaux

**Comment by aroquemaurel** [comment]
![](http://s2.quickmeme.com/img/88/8823b8a8ed2fa43f633c0e6b4f2335b8998d27cfeb30b8068d5c63c75acff962.jpg)
