### ISSUE TITLE
Diaporama

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#216]
Création d'un beamer

**Comment by KraTuX31** [comment]
page de garde rajouter lien vers site web : http://fact-team.github.io/

**Comment by aroquemaurel** [comment]
Good idea ! 

- Ajout d'un diagramme avec le poids en user story, todo, done dans le style de l'image ci-dessous :)
(Cumulative Flow Chart)
![](http://edn.embarcadero.com/article/images/32410/cfd004.png)

**Comment by KraTuX31** [comment]
Lorsqu'on parle du backlog, mettre un lien : https://docs.google.com/spreadsheets/d/1XgOxbuok-wPPwQ3ziozSTOMiaT3ni0giOWk1_Ll4V_Y/edit#gid=0

**Comment by aroquemaurel** [comment]
Finalement le flow cumulatif, c'est le bordel, n'y sera pas ;-)

**Comment by aroquemaurel** [comment]
- Ajouter les issues closed

**Comment by KraTuX31** [comment]
La double casquettes pour TOUS !

**Comment by Oxynos** [comment]
Dans la page mauvais points : 
- Retirer autre et mettre "sous-estimation du poids des sprints"

**Comment by manantsoa** [comment]
Diapo 17:

Sur la capture d'écran, pas de bouton "archiver" pour les clients :/ Prendre une capture d'écran plus récente

**Comment by aroquemaurel** [comment]
Mettre à jour le burn-up.

![image](https://cloud.githubusercontent.com/assets/2221668/7022956/6d4e93c0-dd31-11e4-872c-555b3b24a47d.png)
