### ISSUE TITLE
RAPPORT Bilan Projet

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#217]
Faire un bilan du projet
cf. https://docs.google.com/document/d/1w3BgaoppmO8CeAkEOckb4bqbI4rbkzsSA7omSqDArng/edit

**Comment by aroquemaurel** [comment]
Branche sprint6/217-report

**Comment by KraTuX31** [comment]
Le petit @manantsoa et le petit @aroquemaurel sont attendu à l'acceuil de la rédaction
