### ISSUE TITLE
Plan qualité 

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#42]
Rédaction du plan qualité au format LaTeX

Poids : 5

**Comment by aroquemaurel** [comment]
Gentlemens, je suppose que nous devons mettre le plan qualité sur Moodle ? 
C'est demain la deadline non ? 

Je m'en occupe ? (Recompile, derniers checks, bon nommage, et hop ça part !)

**Comment by manantsoa** [comment]
Oui si tu veux, je pensais qu'on l'avait fait en fait haha ^^
