### ISSUE TITLE
Préparer la soutenance

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#43]
Préparer la soutenance: Diaporama

Poids : 13

**Comment by aroquemaurel** [comment]
@manantsoa @KraTuX31 @Oxynos 
Nous avons pas mal entammés le beamer (thème, quelques slides, et surtout le plan), est-ce qu'on dit que c'est bon qu'on finira à la release suivante, où on avance un peu plus avant de fermer ? :p 

Dans tous les cas, j'ai ouvert la PR #129
