### ISSUE TITLE
Mettre à jour l'arbre des clients

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#63]
Ajouter les projets dans l'arbre des clients ! 
Juste un nœud du dessous.

Suite de l'issue #25

**Comment by manantsoa** [comment]
Double clic sur le noeud "Tous les clients": affiche le tableau des clients
Double clic sur un client: affiche tout les projets du client

**Comment by aroquemaurel** [comment]
Alors là, je dis oui !
![](http://ripostelaique.com/wordpress/wp-content/uploads/2014/09/Lepers.jpg)

Juste un petit « problème » quand on sélectionne un projet dans l'arbre, mais on verra ça quand on aura fait la liste des devis #30 =)

J'intègre.
