### ISSUE TITLE
Seg fault sélectione arbre

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#76]
Une seg fault survient quand on sélectionne un projet dans l'arbre, sans passer par le tableau, alors que ça devrait afficher les factures.

Je pense que cela survient au lancement du logiciel particulièrement.

**Comment by manantsoa** [comment]
Je pense que c'est le même problème que #67 , il n'y a pas de clients sélectionnés alors vu qu'on pas géré ce cas là bah ça plante.

**Comment by aroquemaurel** [comment]
Pas vraiment, parce que ça arrive même si tu as un client sélectionné il me semble… Enfin, suis pas sûr. 

Mais dans tous les cas, il faudrait automatiquement chopper le client parent :)

**Comment by manantsoa** [comment]
Effectivement ça plante si on appuie sur un projet en déroulant le client par l'onglet et pas en cliquant sur le client dans l'arbre qu'un client soit sélectionné ou pas dans le tableau --" Du coup je pensais à enlever l'onglet, concrètement ici il sert à rien non ? Puisque quand on clique sur le client les projets s'affichent automatiquement et on fera sûrement pareil pour les devis ^^

**Comment by Oxynos** [comment]
Voir l'issue #77 et la pull-request associée #84 
Je ferme.
