### ISSUE TITLE
Resolution de bugs mineurs et d'interface

### ISSUE THREAD

**Issue by KraTuX31** [FACT-Team/FactDev#90]
* Mise à jour de la liste des projets (panneau central) lorsqu'on ajoute directement le projet depuis ce panneau.
* Valider un nouveau devis uniquement s'il existe :  (bouton valider en bas "enable" ou "disable")
    - un titre (Promouvoir en CheckUntilField)
    - au moins une contribution
* Nombre d'heure<b>s</b> et non pas Nombre d'heure pour la création d'un devis

**Comment by KraTuX31** [comment]
* Lorsqu'on double clic sur un Projet, on doit voir afficher la liste des devis et sans doublons

**Comment by KraTuX31** [comment]
Pour le précédent commentaire "Lorsqu'on double clic sur un Projet, on doit voir afficher la liste des devis et sans doublons", il suffit de faire un distinct :
"SELECT DISTINCT b.idBilling,title,number,isBilling,date "
             "FROM Billing b, BillingProject bp "
             "WHERE idProject = :idproject "
             "AND b.idBilling = bp.idBilling"

**Comment by aroquemaurel** [comment]
Numéro d'un devis : non initialisé :-(
