### ISSUE TITLE
Bug suppression prestation dans Devis

### ISSUE THREAD

**Issue by aroquemaurel** [FACT-Team/FactDev#98]
Suppression d'une ligne de prestation vide(sans project) bah pas content.

**Comment by aroquemaurel** [comment]
Vient du destructeur d'un projet.
Comment pour la démo.

**Comment by manantsoa** [comment]
La suppression d'une ligne sans projet a l'air de marcher par contre, il plante quand on met des lignes vides et qu'on sauvegarde car oui le bouton Sauvegarder est enable quand on ajoute des lignes vides, faudrait donc qu'on règle ça ;)

**Comment by manantsoa** [comment]
Vu qu'on a tout changé pour les prestations on doit pouvoir fermer celle-là non ?

**Comment by aroquemaurel** [comment]
Bah, y'a toujours le problème en fait :D
